version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: pg-ej2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: parcial_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d parcial_db"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db_data:
