services:
  db:
    image: postgres:16-alpine
    container_name: ej3_db
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"       # útil para conectar desde tu host si lo necesitas
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    networks:
      - app_net

  api:
    build:
      context: ./api
    container_name: ej3_api
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${API_PORT}:3000"
    networks:
      - app_net

volumes:
  db_data:

networks:
  app_net:
